### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by ghost** [slang-legacy/toggleJS#1]
your demo is not working (404) and it would be nice if there was a .html file in the zip file too.

**Comment by notslang** [comment]
Thanks for reporting this issue... I've been meaning to get that demo working, but I haven't had time (and since CSS3 gives us much more advanced styling, these JS based toggle-switch elements are going to be dead soon).

Based on the issues that you've been reporting, it looks like you're looking for a toggle switch like this: https://github.com/ghinda/css-toggle-switch ... take a look at the demo here: http://ghinda.net/css-toggle-switch/
